// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla_Backend.Data;

#nullable disable

namespace Wasla_Backend.data
{
    [DbContext(typeof(Context))]
    [Migration("20260301031152_AddReactionType")]
    partial class AddReactionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountViolations")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsCompleteRegistration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceProviderType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("BaseBookings");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("BaseServices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("bookingDate")
                        .HasColumnType("date");

                    b.Property<int>("bookingStatus")
                        .HasColumnType("int");

                    b.Property<int>("bookingType")
                        .HasColumnType("int");

                    b.Property<string>("imagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("newDayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("newEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("serviceDayId")
                        .HasColumnType("int");

                    b.Property<string>("serviceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("serviceProviderType")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("serviceDayId");

                    b.HasIndex("userId");

                    b.ToTable("DoctorBookings");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ContactUs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("Wasla_Backend.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("DoctorSpecializations");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Favourites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ResidentIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("residentIdentities");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("doctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("doctorId");

                    b.ToTable("DoctorServices");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("end")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBooking")
                        .HasColumnType("bit");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<string>("start")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("serviceId");

                    b.ToTable("ServiceDay");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("postId");

                    b.HasIndex("userId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("fileJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Reaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("reactionType")
                        .HasColumnType("int");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.Property<int>("targetType")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Wasla_Backend.Models.UserEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("eventType")
                        .HasColumnType("int");

                    b.Property<string>("serviceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("serviceProviderId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Resident", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Resident", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.ToTable("ServiceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.GymBooking", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseBooking");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("GymId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GymServiceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsQrUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("QrUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("GymId");

                    b.HasIndex("ServiceId");

                    b.ToTable("GymBookings", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Package", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseService");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<double>("GraduationYear")
                        .HasColumnType("float");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("UniversityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hospitalname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfpatients")
                        .HasColumnType("int");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<float>("CurrentLatitude")
                        .HasColumnType("real");

                    b.Property<float>("CurrentLongitude")
                        .HasColumnType("real");

                    b.Property<int>("DrivingExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Gym", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<string>("imagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("phones")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Gym", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<int>("AverageDeliveryTime")
                        .HasColumnType("int");

                    b.Property<string>("CuisineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeliveryAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MenuItemsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethods")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Restaurant", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationRole", b =>
                {
                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "RoleName", b1 =>
                        {
                            b1.Property<string>("ApplicationRoleId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RoleName_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RoleName_English");

                            b1.HasKey("ApplicationRoleId");

                            b1.ToTable("AspNetRoles");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationRoleId");
                        });

                    b.Navigation("RoleName")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseBooking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseService", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Booking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceDay", "serviceDay")
                        .WithMany()
                        .HasForeignKey("serviceDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serviceDay");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.DoctorSpecialization", b =>
                {
                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Specialization", b1 =>
                        {
                            b1.Property<int>("DoctorSpecializationId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Specialization_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Specialization_English");

                            b1.HasKey("DoctorSpecializationId");

                            b1.ToTable("DoctorSpecializations");

                            b1.WithOwner()
                                .HasForeignKey("DoctorSpecializationId");
                        });

                    b.Navigation("Specialization")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Favourites", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Payment", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Reviews", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Doctor", "doctor")
                        .WithMany("services")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "description", b1 =>
                        {
                            b1.Property<int>("Serviceid")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description_English");

                            b1.HasKey("Serviceid");

                            b1.ToTable("DoctorServices");

                            b1.WithOwner()
                                .HasForeignKey("Serviceid");
                        });

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "serviceName", b1 =>
                        {
                            b1.Property<int>("Serviceid")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("serviceName_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("serviceName_English");

                            b1.HasKey("Serviceid");

                            b1.ToTable("DoctorServices");

                            b1.WithOwner()
                                .HasForeignKey("Serviceid");
                        });

                    b.Navigation("description");

                    b.Navigation("doctor");

                    b.Navigation("serviceName");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceDay", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Service", "service")
                        .WithMany("ServiceDays")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Comment", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Social.Post", "post")
                        .WithMany("comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Post", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Reaction", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.UserEvent", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", "serviceProvider")
                        .WithMany()
                        .HasForeignKey("serviceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serviceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Resident", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Resident", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.ServiceProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.GymBooking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.GymModel.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseBooking", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.GymBooking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.GymModel.Package", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Package", b =>
                {
                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseService", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.Package", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Description", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description_English");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Name", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_English");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.DoctorSpecialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Gym", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.Gym", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Restaurant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.Navigation("ServiceDays");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Post", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.Navigation("services");
                });
#pragma warning restore 612, 618
        }
    }
}
